version: "3"
services:
  orion:
    image: fiware/orion-ld 
    container_name: orionld
    ports:
      - 1026:1026
    depends_on:
      - oriondb
    command: -dbhost oriondb -logLevel DEBUG
    restart: always
  oriondb:
    image: mongo
    container_name: oriondb
    command: --nojournal
